compass:
  servers:
    build:
      material: STONE_BRICKS
      display: Build
      lore: Click me to join our Build server.
    survival:
      material: IRON_PICKAXE
      display: Survival
      lore: Click me to join our Survival server.
    mixed:
      material: IRON_SWORD
      display: Mixed
      lore: Play and Destroy your friends in Minigames.
    events:
      material: NETHER_STAR
      display: Events
      lore: Click me to join our Events server.
    creative:
      material: GRASS_BLOCK
      display: Creative
      lore: Click me to join our Creative server.
messages:
  join: '&7%p% joined.'
  leave: '&7%p% left.'
misc:
  always_first_join: false
  slot_hub_compass: 4
velocitymultiplier: 3
hub:
  world: world
  x: 0.5
  y: 129.0
  z: 0.5
  yaw: -180.0
  pitch: 0.0
