/**
 * Event Template Service
 * Manages recurring event templates and draft generation pipeline.
 */

import { prisma } from "../controllers/databaseController.js";
import { createEvent, logEventAudit, upsertEventAnnouncements } from "./eventService.js";

/**
 * Get all active templates.
 */
export async function getTemplates({ includeDeleted = false } = {}) {
  const where = {};
  if (!includeDeleted) where.deletedAt = null;

  return prisma.event_templates.findMany({
    where,
    include: { defaultHosts: true, _count: { select: { events: true } } },
    orderBy: { createdAt: "asc" },
  });
}

/**
 * Get a single template by ID.
 */
export async function getTemplateById(templateId, includeDeleted = false) {
  const tmpl = await prisma.event_templates.findUnique({
    where: { templateId: parseInt(templateId) },
    include: {
      defaultHosts: true,
      announcements: { orderBy: { id: "asc" } },
      events: {
        where: { deletedAt: null },
        orderBy: { startAt: "desc" },
        take: 10,
        select: { eventId: true, title: true, startAt: true, status: true },
      },
    },
  });

  if (!tmpl) return null;
  if (!includeDeleted && tmpl.deletedAt) return null;

  return tmpl;
}

/**
 * Create a new event template.
 */
export async function createTemplate(data, creatorId) {
  const tmpl = await prisma.event_templates.create({
    data: {
      title: data.title,
      description: data.description || null,
      defaultStartTime: data.defaultStartTime || null,
      defaultEndTime: data.defaultEndTime || null,
      defaultDurationMins: data.defaultDurationMins || null,
      timezone: data.timezone || "UTC",
      recurrenceType: data.recurrenceType || "weekly",
      recurrenceDays: data.recurrenceDays || undefined,
      recurrenceEveryDays: data.recurrenceEveryDays || null,
      draftAdvanceDays: data.draftAdvanceDays || 7,
      autoGenerateDrafts: data.autoGenerateDrafts !== undefined ? data.autoGenerateDrafts : true,
      locationLabel: data.locationLabel || null,
      locationType: data.locationType || null,
      locationDiscordChannelId: data.locationDiscordChannelId || null,
      serverName: data.serverName || null,
      serverIp: data.serverIp || null,
      bannerUrl: data.bannerUrl || null,
      logoUrl: data.logoUrl || null,
      tags: data.tags || undefined,
      creatorId,
      isActive: true,
    },
  });

  // Create default hosts
  if (Array.isArray(data.defaultHosts) && data.defaultHosts.length > 0) {
    await prisma.event_template_hosts.createMany({
      data: data.defaultHosts.map((h) => ({
        templateId: tmpl.templateId,
        userId: h.userId ? parseInt(h.userId) : null,
        discordUserId: h.discordUserId || null,
        displayName: h.displayName || null,
        role: h.role || "host",
      })),
    });
  }

  // Compute first nextGenerateAt
  const nextDate = computeNextGenerationDate(tmpl);
  if (nextDate) {
    await prisma.event_templates.update({
      where: { templateId: tmpl.templateId },
      data: { nextGenerateAt: nextDate },
    });
  }

  return tmpl;
}

/**
 * Update an existing template.
 */
export async function updateTemplate(templateId, data, actorId) {
  const updateData = {};

  if (data.title !== undefined) updateData.title = data.title;
  if (data.description !== undefined) updateData.description = data.description;
  if (data.defaultStartTime !== undefined) updateData.defaultStartTime = data.defaultStartTime;
  if (data.defaultEndTime !== undefined) updateData.defaultEndTime = data.defaultEndTime;
  if (data.defaultDurationMins !== undefined) updateData.defaultDurationMins = data.defaultDurationMins;
  if (data.timezone !== undefined) updateData.timezone = data.timezone;
  if (data.recurrenceType !== undefined) updateData.recurrenceType = data.recurrenceType;
  if (data.recurrenceDays !== undefined) updateData.recurrenceDays = data.recurrenceDays;
  if (data.recurrenceEveryDays !== undefined) updateData.recurrenceEveryDays = data.recurrenceEveryDays;
  if (data.draftAdvanceDays !== undefined) updateData.draftAdvanceDays = data.draftAdvanceDays;
  if (data.autoGenerateDrafts !== undefined) updateData.autoGenerateDrafts = data.autoGenerateDrafts;
  if (data.locationLabel !== undefined) updateData.locationLabel = data.locationLabel;
  if (data.locationType !== undefined) updateData.locationType = data.locationType || null;
  if (data.locationDiscordChannelId !== undefined) updateData.locationDiscordChannelId = data.locationDiscordChannelId || null;
  if (data.serverName !== undefined) updateData.serverName = data.serverName;
  if (data.serverIp !== undefined) updateData.serverIp = data.serverIp;
  if (data.bannerUrl !== undefined) updateData.bannerUrl = data.bannerUrl;
  if (data.logoUrl !== undefined) updateData.logoUrl = data.logoUrl;
  if (data.tags !== undefined) updateData.tags = data.tags;
  if (data.isActive !== undefined) updateData.isActive = data.isActive;

  const updated = await prisma.event_templates.update({
    where: { templateId: parseInt(templateId) },
    data: updateData,
  });

  // Update default hosts
  if (Array.isArray(data.defaultHosts)) {
    await prisma.event_template_hosts.deleteMany({ where: { templateId: parseInt(templateId) } });
    if (data.defaultHosts.length > 0) {
      await prisma.event_template_hosts.createMany({
        data: data.defaultHosts.map((h) => ({
          templateId: parseInt(templateId),
          userId: h.userId ? parseInt(h.userId) : null,
          discordUserId: h.discordUserId || null,
          displayName: h.displayName || null,
          role: h.role || "host",
        })),
      });
    }
  }

  // Recompute nextGenerateAt
  const nextDate = computeNextGenerationDate(updated);
  if (nextDate) {
    await prisma.event_templates.update({
      where: { templateId: parseInt(templateId) },
      data: { nextGenerateAt: nextDate },
    });
  }

  return updated;
}

/**
 * Soft-delete a template.
 */
export async function deleteTemplate(templateId) {
  return prisma.event_templates.update({
    where: { templateId: parseInt(templateId) },
    data: { deletedAt: new Date(), isActive: false },
  });
}

/**
 * Generate a draft event from a template.
 * The event inherits template defaults but remains fully editable.
 */
export async function generateDraftFromTemplate(template, targetDate, actorId = null, actorName = "System") {
  const { defaultStartTime, defaultEndTime, defaultDurationMins, timezone } = template;

  // Build start/end datetimes for the target date in the template's timezone
  // We store UTC; targetDate is a JS Date already set to the occurrence date (midnight UTC)
  const dateStr = targetDate.toISOString().slice(0, 10);

  const startTime = defaultStartTime || "18:00:00";
  const endTime = defaultEndTime || null;

  // Parse times as UTC (no conversion; operators should configure times in UTC or use timezone field)
  const startAt = new Date(`${dateStr}T${startTime}Z`);
  let endAt;

  if (endTime) {
    endAt = new Date(`${dateStr}T${endTime}Z`);
    // Handle overnight events
    if (endAt <= startAt) endAt = new Date(endAt.getTime() + 86400000);
  } else if (defaultDurationMins) {
    endAt = new Date(startAt.getTime() + defaultDurationMins * 60000);
  } else {
    endAt = new Date(startAt.getTime() + 3600000); // default 1 hour
  }

  const eventData = {
    title: template.title,
    description: template.description,
    eventType: "standard",
    startAt: startAt.toISOString(),
    endAt: endAt.toISOString(),
    timezone,
    locationLabel: template.locationLabel,
    serverName: template.serverName,
    serverIp: template.serverIp,
    bannerUrl: template.bannerUrl,
    logoUrl: template.logoUrl,
    tags: template.tags,
    templateId: template.templateId,
    hosts: (template.defaultHosts || []).map((h) => ({
      userId: h.userId,
      discordUserId: h.discordUserId,
      displayName: h.displayName,
      role: h.role,
    })),
  };

  const creatorId = actorId || template.creatorId;
  const event = await createEvent(eventData, creatorId, actorName);

  // Copy template announcements to the new event
  if (Array.isArray(template.announcements) && template.announcements.length > 0) {
    await upsertEventAnnouncements(
      event.eventId,
      template.announcements.map((a) => ({
        label: a.label,
        announcementType: a.announcementType,
        platform: a.platform,
        channelId: a.channelId,
        contentTemplate: a.contentTemplate,
        body: a.body,
        colourMessageFormat: a.colourMessageFormat,
        link: a.link,
        popupButtonText: a.popupButtonText,
        popupImageUrl: a.popupImageUrl,
        triggerType: a.triggerType,
        offsetMinutes: a.offsetMinutes,
        enabled: a.enabled,
      })),
      creatorId,
      actorName
    );
  }

  await logEventAudit(
    event.eventId,
    creatorId,
    actorName,
    "template_generated",
    `Draft generated from template #${template.templateId}: "${template.title}"`
  );

  return event;
}

/**
 * Replace all announcements for a template (delete + recreate).
 */
export async function upsertTemplateAnnouncements(templateId, announcements) {
  await prisma.event_template_announcements.deleteMany({
    where: { templateId: parseInt(templateId) },
  });

  if (Array.isArray(announcements) && announcements.length > 0) {
    await prisma.event_template_announcements.createMany({
      data: announcements.map((a) => ({
        templateId: parseInt(templateId),
        label: a.label || null,
        announcementType: a.announcementType || "reminder",
        platform: a.platform || "discord",
        channelId: a.channelId || null,
        contentTemplate: a.contentTemplate || null,
        body: a.body || null,
        colourMessageFormat: a.colourMessageFormat || null,
        link: a.link || null,
        popupButtonText: a.popupButtonText || null,
        popupImageUrl: a.popupImageUrl || null,
        triggerType: a.triggerType || "before_event",
        offsetMinutes: a.offsetMinutes ? parseInt(a.offsetMinutes) : null,
        enabled: a.enabled !== undefined ? a.enabled : true,
      })),
    });
  }
}

/**
 * Compute the next date that a template should generate a draft.
 * Returns a Date or null.
 */
export function computeNextGenerationDate(template, fromDate = null) {
  const base = fromDate ? new Date(fromDate) : new Date();

  if (!template.autoGenerateDrafts) return null;

  const advanceDays = template.draftAdvanceDays || 7;

  if (template.recurrenceType === "weekly" && Array.isArray(template.recurrenceDays)) {
    const days = template.recurrenceDays.map(Number).sort();
    if (days.length === 0) return null;

    // Find the next occurrence that is at least advanceDays in the future
    const targetEventDate = new Date(base.getTime() + advanceDays * 86400000);
    const targetDay = targetEventDate.getUTCDay();

    // Find soonest day-of-week >= targetDay, then wrap
    for (let offset = 0; offset < 7; offset++) {
      const checkDay = (targetDay + offset) % 7;
      if (days.includes(checkDay)) {
        const result = new Date(targetEventDate);
        const diff = ((checkDay - targetDay) + 7) % 7;
        result.setUTCDate(result.getUTCDate() + diff);
        result.setUTCHours(0, 0, 0, 0);
        // The draft should be generated now (today), the event is on result
        // So generate trigger = result - advanceDays
        const generateOn = new Date(result.getTime() - advanceDays * 86400000);
        // If generateOn is not strictly in the future, advance by one week
        if (generateOn <= base) {
          result.setUTCDate(result.getUTCDate() + 7);
          return new Date(result.getTime() - advanceDays * 86400000);
        }
        return generateOn;
      }
    }
  }

  if (template.recurrenceType === "daily") {
    // Schedule the next generation for the following day at midnight UTC
    const next = new Date(base);
    next.setUTCDate(next.getUTCDate() + 1);
    next.setUTCHours(0, 0, 0, 0);
    return next;
  }

  if (template.recurrenceType === "custom" && template.recurrenceEveryDays) {
    const every = template.recurrenceEveryDays;
    // Anchor the next generation to the current generation time
    const next = new Date(base.getTime() + every * 86400000);
    return next;
  }

  return null;
}

/**
 * Find the next event occurrence date for a template.
 */
export function computeNextEventDate(template, fromDate = null) {
  const base = fromDate ? new Date(fromDate) : new Date();
  base.setUTCHours(0, 0, 0, 0);

  if (template.recurrenceType === "weekly" && Array.isArray(template.recurrenceDays)) {
    const days = template.recurrenceDays.map(Number).sort();
    if (days.length === 0) return null;

    const currentDay = base.getUTCDay();
    for (let offset = 1; offset <= 7; offset++) {
      const checkDay = (currentDay + offset) % 7;
      if (days.includes(checkDay)) {
        const next = new Date(base);
        next.setUTCDate(next.getUTCDate() + offset);
        return next;
      }
    }
  }

  if (template.recurrenceType === "daily") {
    const next = new Date(base);
    next.setUTCDate(next.getUTCDate() + 1);
    return next;
  }

  if (template.recurrenceType === "custom" && template.recurrenceEveryDays) {
    const last = template.lastGeneratedAt ? new Date(template.lastGeneratedAt) : base;
    const next = new Date(last.getTime() + template.recurrenceEveryDays * 86400000);
    return next;
  }

  return null;
}

/**
 * Get all templates due for draft generation.
 */
export async function getTemplatesDueForGeneration() {
  const now = new Date();
  return prisma.event_templates.findMany({
    where: {
      isActive: true,
      deletedAt: null,
      autoGenerateDrafts: true,
      nextGenerateAt: { lte: now },
    },
    include: { defaultHosts: true, announcements: { orderBy: { id: "asc" } } },
  });
}

/**
 * Soft-delete template-generated events that are still in draft/pending_review
 * and whose startAt has already passed. These are "unused" events that were
 * auto-created but never promoted before their scheduled time.
 *
 * Returns the count of deleted events.
 */
export async function cleanupStaleTemplateEvents() {
  const now = new Date();

  const stale = await prisma.events.findMany({
    where: {
      templateId: { not: null },
      status: { in: ["draft", "pending_review"] },
      startAt: { lt: now },
      deletedAt: null,
    },
    select: { eventId: true, title: true, templateId: true },
  });

  if (stale.length === 0) return 0;

  await prisma.events.updateMany({
    where: { eventId: { in: stale.map((e) => e.eventId) } },
    data: { deletedAt: now },
  });

  return stale.length;
}

/**
 * Mark a template as having just generated a draft and set the next generation time.
 */
export async function markTemplateGenerated(templateId, generatedAt = new Date()) {
  const tmpl = await prisma.event_templates.findUnique({
    where: { templateId: parseInt(templateId) },
  });

  if (!tmpl) return;

  const nextGenerate = computeNextGenerationDate(tmpl, generatedAt);

  return prisma.event_templates.update({
    where: { templateId: parseInt(templateId) },
    data: {
      lastGeneratedAt: generatedAt,
      nextGenerateAt: nextGenerate || null,
    },
  });
}
