-- CreateTable: Events Calendar Module
-- Migration: 0006_events_calendar

CREATE TABLE `events` (
    `eventId` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `slug` VARCHAR(300) NOT NULL,
    `description` LONGTEXT NULL,
    `eventType` VARCHAR(32) NOT NULL DEFAULT 'once',
    `startAt` DATETIME(3) NOT NULL,
    `endAt` DATETIME(3) NOT NULL,
    `timezone` VARCHAR(64) NOT NULL DEFAULT 'UTC',
    `status` VARCHAR(32) NOT NULL DEFAULT 'draft',
    `visibility` VARCHAR(32) NOT NULL DEFAULT 'public',
    `locationLabel` VARCHAR(255) NULL,
    `serverName` VARCHAR(255) NULL,
    `serverIp` VARCHAR(255) NULL,
    `externalLinks` JSON NULL,
    `bannerUrl` VARCHAR(512) NULL,
    `logoUrl` VARCHAR(512) NULL,
    `tags` JSON NULL,
    `featured` BOOLEAN NOT NULL DEFAULT false,
    `creatorId` INTEGER NOT NULL,
    `reviewerId` INTEGER NULL,
    `templateId` INTEGER NULL,
    `rejectionNote` TEXT NULL,
    `discordMessageId` VARCHAR(32) NULL,
    `discordGuildEventId` VARCHAR(32) NULL,
    `discordChannelId` VARCHAR(32) NULL,
    `discordSyncStatus` VARCHAR(16) NULL,
    `discordSyncError` TEXT NULL,
    `websiteSyncStatus` VARCHAR(16) NULL,
    `websiteSyncError` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `approvedAt` DATETIME(3) NULL,
    `publishedAt` DATETIME(3) NULL,
    `cancelledAt` DATETIME(3) NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `events_slug_key`(`slug`),
    PRIMARY KEY (`eventId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `event_templates` (
    `templateId` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `description` LONGTEXT NULL,
    `defaultStartTime` VARCHAR(8) NULL,
    `defaultEndTime` VARCHAR(8) NULL,
    `defaultDurationMins` INTEGER NULL,
    `timezone` VARCHAR(64) NOT NULL DEFAULT 'UTC',
    `recurrenceType` VARCHAR(32) NOT NULL DEFAULT 'weekly',
    `recurrenceDays` JSON NULL,
    `recurrenceEveryDays` INTEGER NULL,
    `draftAdvanceDays` INTEGER NOT NULL DEFAULT 7,
    `autoGenerateDrafts` BOOLEAN NOT NULL DEFAULT true,
    `lastGeneratedAt` DATETIME(3) NULL,
    `nextGenerateAt` DATETIME(3) NULL,
    `locationLabel` VARCHAR(255) NULL,
    `serverName` VARCHAR(255) NULL,
    `serverIp` VARCHAR(255) NULL,
    `bannerUrl` VARCHAR(512) NULL,
    `logoUrl` VARCHAR(512) NULL,
    `tags` JSON NULL,
    `creatorId` INTEGER NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `deletedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`templateId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `event_template_hosts` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `templateId` INTEGER NOT NULL,
    `userId` INTEGER NULL,
    `discordUserId` VARCHAR(32) NULL,
    `displayName` VARCHAR(100) NULL,
    `role` VARCHAR(32) NOT NULL DEFAULT 'host',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `event_hosts` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `eventId` INTEGER NOT NULL,
    `userId` INTEGER NULL,
    `discordUserId` VARCHAR(32) NULL,
    `displayName` VARCHAR(100) NULL,
    `role` VARCHAR(32) NOT NULL DEFAULT 'host',

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `event_actions` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `eventId` INTEGER NOT NULL,
    `actionType` VARCHAR(32) NOT NULL,
    `trigger` VARCHAR(32) NOT NULL DEFAULT 'on_publish',
    `enabled` BOOLEAN NOT NULL DEFAULT true,
    `config` JSON NULL,
    `lastRunAt` DATETIME(3) NULL,
    `lastRunStatus` VARCHAR(16) NULL,
    `lastRunError` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `event_announcements` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `eventId` INTEGER NOT NULL,
    `label` VARCHAR(100) NULL,
    `announcementType` VARCHAR(32) NOT NULL DEFAULT 'reminder',
    `platform` VARCHAR(32) NOT NULL DEFAULT 'discord',
    `channelId` VARCHAR(32) NULL,
    `contentTemplate` TEXT NULL,
    `triggerType` VARCHAR(32) NOT NULL DEFAULT 'before_event',
    `offsetMinutes` INTEGER NULL,
    `scheduledFor` DATETIME(3) NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT true,
    `status` VARCHAR(16) NOT NULL DEFAULT 'pending',
    `sentAt` DATETIME(3) NULL,
    `lastError` TEXT NULL,
    `discordMessageId` VARCHAR(32) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `event_audit_logs` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `eventId` INTEGER NOT NULL,
    `actorId` INTEGER NULL,
    `actorName` VARCHAR(100) NULL,
    `action` VARCHAR(64) NOT NULL,
    `details` TEXT NULL,
    `beforeSnapshot` JSON NULL,
    `afterSnapshot` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `events` ADD CONSTRAINT `events_templateId_fkey` FOREIGN KEY (`templateId`) REFERENCES `event_templates`(`templateId`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `event_template_hosts` ADD CONSTRAINT `event_template_hosts_templateId_fkey` FOREIGN KEY (`templateId`) REFERENCES `event_templates`(`templateId`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `event_hosts` ADD CONSTRAINT `event_hosts_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `event_actions` ADD CONSTRAINT `event_actions_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `event_announcements` ADD CONSTRAINT `event_announcements_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `event_audit_logs` ADD CONSTRAINT `event_audit_logs_eventId_fkey` FOREIGN KEY (`eventId`) REFERENCES `events`(`eventId`) ON DELETE CASCADE ON UPDATE CASCADE;
